"""SQLite schema for append-only YTQJK identity records."""

SCHEMA = """
CREATE TABLE IF NOT EXISTS metadata (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS runs (run_id TEXT PRIMARY KEY, session_key TEXT NOT NULL, project_id TEXT NOT NULL, objective_hash TEXT NOT NULL, database_id TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS run_events (run_id TEXT NOT NULL REFERENCES runs(run_id), version INTEGER NOT NULL, state TEXT NOT NULL CHECK(state IN ('RUNNING','PAUSED','STOPPED','DONE','BLOCKED')), created_at INTEGER NOT NULL, PRIMARY KEY(run_id, version));
CREATE TABLE IF NOT EXISTS role_ledger (run_id TEXT NOT NULL REFERENCES runs(run_id), session_key TEXT NOT NULL, role TEXT NOT NULL, read_scope TEXT NOT NULL, write_scope TEXT NOT NULL, mutation INTEGER NOT NULL CHECK(mutation IN (0,1)), capabilities TEXT NOT NULL, created_at INTEGER NOT NULL, CHECK(capabilities = '[]' OR (role IN ('director','controller') AND capabilities = '["run:lifecycle"]')), CHECK(role NOT IN ('director','controller') OR (read_scope = '[]' AND write_scope = '[]' AND mutation = 0)), PRIMARY KEY(run_id, session_key, role));
CREATE TABLE IF NOT EXISTS lease_events (lease_id TEXT NOT NULL, run_id TEXT NOT NULL REFERENCES runs(run_id), session_key TEXT NOT NULL, role TEXT NOT NULL, version INTEGER NOT NULL, state TEXT NOT NULL CHECK(state IN ('ACTIVE','CONSUMED','REVOKED','EXPIRED')), expires_at INTEGER NOT NULL, binding_hash TEXT NOT NULL, created_at INTEGER NOT NULL, PRIMARY KEY(lease_id, version));
CREATE TABLE IF NOT EXISTS audit_events (event_id INTEGER PRIMARY KEY AUTOINCREMENT, created_at INTEGER NOT NULL, kind TEXT NOT NULL, run_id TEXT NOT NULL, session_key TEXT NOT NULL, lease_id TEXT, detail TEXT NOT NULL);
CREATE TRIGGER IF NOT EXISTS no_metadata_update BEFORE UPDATE ON metadata BEGIN SELECT RAISE(ABORT, 'immutable ledger'); END;
CREATE TRIGGER IF NOT EXISTS no_metadata_delete BEFORE DELETE ON metadata BEGIN SELECT RAISE(ABORT, 'immutable ledger'); END;
CREATE TRIGGER IF NOT EXISTS no_runs_update BEFORE UPDATE ON runs BEGIN SELECT RAISE(ABORT, 'immutable ledger'); END;
CREATE TRIGGER IF NOT EXISTS no_runs_delete BEFORE DELETE ON runs BEGIN SELECT RAISE(ABORT, 'immutable ledger'); END;
CREATE TRIGGER IF NOT EXISTS no_run_events_update BEFORE UPDATE ON run_events BEGIN SELECT RAISE(ABORT, 'append only'); END;
CREATE TRIGGER IF NOT EXISTS no_run_events_delete BEFORE DELETE ON run_events BEGIN SELECT RAISE(ABORT, 'append only'); END;
CREATE TRIGGER IF NOT EXISTS valid_run_transition BEFORE INSERT ON run_events BEGIN SELECT CASE WHEN (NEW.version = 0 AND NEW.state = 'RUNNING') OR (NEW.version > 0 AND EXISTS (SELECT 1 FROM run_events old WHERE old.run_id = NEW.run_id AND old.version = NEW.version - 1 AND ((old.state = 'RUNNING' AND NEW.state IN ('PAUSED','STOPPED','DONE','BLOCKED')) OR (old.state = 'PAUSED' AND NEW.state IN ('RUNNING','STOPPED','DONE','BLOCKED'))))) THEN 1 ELSE RAISE(ABORT, 'invalid run transition') END; END;
CREATE TRIGGER IF NOT EXISTS run_close_requires_revocation BEFORE INSERT ON run_events WHEN NEW.state != 'RUNNING' BEGIN SELECT CASE WHEN EXISTS (SELECT 1 FROM lease_events current JOIN (SELECT lease_id, MAX(version) version FROM lease_events GROUP BY lease_id) latest ON current.lease_id = latest.lease_id AND current.version = latest.version WHERE current.run_id = NEW.run_id AND current.state = 'ACTIVE') THEN RAISE(ABORT, 'active lease must be revoked') END; END;
CREATE TRIGGER IF NOT EXISTS no_roles_update BEFORE UPDATE ON role_ledger BEGIN SELECT RAISE(ABORT, 'immutable ledger'); END;
CREATE TRIGGER IF NOT EXISTS no_roles_delete BEFORE DELETE ON role_ledger BEGIN SELECT RAISE(ABORT, 'immutable ledger'); END;
CREATE TRIGGER IF NOT EXISTS role_matches_run BEFORE INSERT ON role_ledger BEGIN SELECT CASE WHEN EXISTS (SELECT 1 FROM runs WHERE run_id = NEW.run_id AND session_key = NEW.session_key) THEN 1 ELSE RAISE(ABORT, 'role session mismatch') END; END;
CREATE TRIGGER IF NOT EXISTS director_zero_task_power BEFORE INSERT ON role_ledger WHEN NEW.role IN ('director','controller') BEGIN SELECT CASE WHEN NEW.read_scope = '[]' AND NEW.write_scope = '[]' AND NEW.mutation = 0 AND NEW.capabilities IN ('[]','["run:lifecycle"]') THEN 1 ELSE RAISE(ABORT, 'director coordination only') END; END;
CREATE TRIGGER IF NOT EXISTS no_lease_events_update BEFORE UPDATE ON lease_events BEGIN SELECT RAISE(ABORT, 'append only'); END;
CREATE TRIGGER IF NOT EXISTS no_lease_events_delete BEFORE DELETE ON lease_events BEGIN SELECT RAISE(ABORT, 'append only'); END;
CREATE TRIGGER IF NOT EXISTS valid_lease_transition BEFORE INSERT ON lease_events BEGIN SELECT CASE WHEN (NEW.version = 0 AND NEW.state = 'ACTIVE') OR (NEW.version > 0 AND EXISTS (SELECT 1 FROM lease_events old WHERE old.lease_id = NEW.lease_id AND old.version = NEW.version - 1 AND old.run_id = NEW.run_id AND old.session_key = NEW.session_key AND old.role = NEW.role AND old.state = 'ACTIVE' AND NEW.state IN ('CONSUMED','REVOKED','EXPIRED'))) THEN 1 ELSE RAISE(ABORT, 'invalid lease transition') END; END;
CREATE TRIGGER IF NOT EXISTS lease_matches_role BEFORE INSERT ON lease_events WHEN NEW.version = 0 BEGIN SELECT CASE WHEN EXISTS (SELECT 1 FROM role_ledger WHERE run_id = NEW.run_id AND session_key = NEW.session_key AND role = NEW.role) THEN 1 ELSE RAISE(ABORT, 'lease role mismatch') END; END;
CREATE TRIGGER IF NOT EXISTS no_audit_update BEFORE UPDATE ON audit_events BEGIN SELECT RAISE(ABORT, 'append only'); END;
CREATE TRIGGER IF NOT EXISTS no_audit_delete BEFORE DELETE ON audit_events BEGIN SELECT RAISE(ABORT, 'append only'); END;
"""
